#!/usr/bin/env bash
# Reads /etc/passwd and tells a short story about each user (uses while + IFS)

while IFS=: read -r username password user_id group_id user_info home_dir shell || [ -n "$username" ]; do
    echo "The user $username is part of the $group_id gang, lives in $home_dir and rides $shell. ${user_id}'s place is protected by the passcode $password, more info about the user here: $user_info"
done < /etc/passwd