#!/usr/bin/env bash
# This script reads the /etc/passwd file and prints a story about each user, using ":" as a delimiter

while IFS=":" read username password uid gid home shell
do
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $info"

done < /etc/passwd
