#!/usr/bin/env bash
# Prints hours 0 to 12, and for each hour the minutes 1 to 59 (uses while loops)

h=0
while [ $h -le 12 ]
do
    echo "Hour: $h"
    m=1
    while [ $m -le 59 ];
    do
        echo "$m"
        m=$((m + 1))
    done
    h=$((h + 1))
done
