#!/usr/bin/env bash
# This script checks if a file exists, is not empty, and is a regular file

school="school"
if [ -e "$school" ]; then
    echo "$school file exists"

    echo "$school file does not exist"


    if [ -s "$school" ]; then
        echo "$school file is not empty"
    else
        echo "$school file is empty"
    fi

    if [-f "$school" ]; then
        echo "$school is a regular file"
    fi
else
    echo "$school file does not exist"
fi
